In [2]:
# Format bridge table track_genre
import pandas as pd
import numpy as np
import ast 
# import dataset
df = pd.read_csv(r"C:\Users\Utilisateur\Documents\spotify\charts.csv", encoding="ISO-8859-1", sep=";")
df

,date,country,position,streams,track_id,artists,artist_genres,duration,explicit,name
0,10/11/2022,au,169,280161,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,FAUX,Wake Me Up
1,10/11/2022,be,182,59603,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,FAUX,Wake Me Up
2,10/11/2022,ie,184,46016,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,FAUX,Wake Me Up
3,10/11/2022,cz,198,43421,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,FAUX,Wake Me Up
4,03/11/2022,be,159,62915,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,FAUX,Wake Me Up
...,...,...,...,...,...,...,...,...,...,...
1048570,11/06/2015,pl,336,1557,48q0vSHcJdhK3IiXH8C5WJ,['Arctic Monkeys'],"['permanent wave', 'modern rock', 'rock', 'gar...",161123,FAUX,Why'd You Only Call Me When You're High?
1048571,11/06/2015,pl,338,1534,7CFQrZR4WeKEg4vweqp8Gv,['Ellie Goulding'],"['edm', 'pop', 'metropopolis', 'uk pop', 'elec...",154435,FAUX,How Long Will I Love You - Bonus Track
1048572,11/06/2015,tw,340,1145,6ybViy2qrO9sIi41EgRJgx,['Norah Jones'],"['neo mellow', 'contemporary vocal jazz', 'jaz...",186146,FAUX,Don't Know Why
1048573,25/06/2015,tw,342,1162,4kKOvNj0AsVNc10cfPcEQh,['Jasmine Thompson'],"['viral pop', 'pop', 'neo mellow']",225976,FAUX,Thinking out Loud
1048574,25/06/2015,tw,344,1153,0kb10fZdI2pvDKY3zc0Gs1,['Villagers'],"['stomp and holler', 'chamber pop', 'indie roc...",219093,FAUX,Nothing Arrived - Live from Spotify London

In [3]:
# date filter on the last 5 years and convert into year
df['date'] = pd.to_datetime(df['date'], format='%d/%m/%Y')
df = df.loc[df['date'] > '2020-12-31'].copy()
df['date'] = df['date'].dt.year
print(df.head())

   date country  position  streams                track_id     artists  \
0  2022      au       169   280161  0nrRP2bk19rLc0orkWPQk2  ['Avicii']
1  2022      be       182    59603  0nrRP2bk19rLc0orkWPQk2  ['Avicii']
2  2022      ie       184    46016  0nrRP2bk19rLc0orkWPQk2  ['Avicii']
3  2022      cz       198    43421  0nrRP2bk19rLc0orkWPQk2  ['Avicii']
4  2022      be       159    62915  0nrRP2bk19rLc0orkWPQk2  ['Avicii']

                                       artist_genres  duration explicit  \
0  ['pop rap', 'pop', 'pop dance', 'dance pop', '...    247426     FAUX
1  ['pop rap', 'pop', 'pop dance', 'dance pop', '...    247426     FAUX
2  ['pop rap', 'pop', 'pop dance', 'dance pop', '...    247426     FAUX
3  ['pop rap', 'pop', 'pop dance', 'dance pop', '...    247426     FAUX
4  ['pop rap', 'pop', 'pop dance', 'dance pop', '...    247426     FAUX

         name
0  Wake Me Up
1  Wake Me Up
2  Wake Me Up
3  Wake Me Up
4  Wake Me Up

In [4]:
# return string as a list
import ast

def safe_eval_genre(s):
    try:
        return ast.literal_eval(s)
    except:
        return []

df['artist_genres_list'] = df['artist_genres'].apply(safe_eval_genre)

In [5]:
df['artist_genres_list']

0                  [pop rap, pop, pop dance, dance pop, edm]
1                  [pop rap, pop, pop dance, dance pop, edm]
2                  [pop rap, pop, pop dance, dance pop, edm]
3                  [pop rap, pop, pop dance, dance pop, edm]
4                  [pop rap, pop, pop dance, dance pop, edm]
                                 ...
1043366                             [panamanian pop, tipico]
1043367               [korean singer-songwriter, korean pop]
1043376             [chalga, macedonian folk, bulgarian pop]
1043379    [spanish pop, italian pop, latin pop, pop vira...
1043385                        [latin pop, puerto rican pop]
Name: artist_genres_list, Length: 275572, dtype: object

In [6]:
genre_map = {
    "pop": ["pop", "pop rap", "pop dance", "dance pop", "electropop", "uk pop", "viral pop", "canadian pop"],
    "hip hop/rap": ["hip hop", "rap", "trap", "pop rap", "latin hip hop", "southern hip hop", "gangster rap"],
    "electronic/dance": ["edm", "electro house", "house", "progressive house", "tropical house", "trance", "complextro"],
    "latin": ["reggaeton", "bachata", "cumbia", "latin pop", "urbano latino"],
    "r&b/soul": ["r&b", "neo soul", "contemporary r&b", "chill r&b", "pop r&b"],
    "rock": ["rock", "pop rock", "modern rock", "alternative rock", "indie rock"],
    "country/folk": ["country", "country pop", "folk pop"],
    "global/regional": ["k-pop", "j-pop", "mandopop", "italian pop", "french pop"],
    "alternative/indie": ["indie pop", "indie poptimism", "bedroom pop", "alt z", "art pop"],
    "reggae/dancehall": ["dancehall", "moombahton", "tropical"]
}

In [7]:
def assign_main_genre(genres):
    if not genres:
        return "Other"
    
    genres = [g.lower() for g in genres]
    
    for main_genre, subgenres in genre_map.items():
        for sub in subgenres:
            if any(sub == g or sub in g for g in genres):
                return main_genre.capitalize()
    return "Other"

In [8]:
df['main_genre'] = df['artist_genres_list'].apply(assign_main_genre)

In [35]:
df.head()

,date,country,position,streams,track_id,artists,artist_genres,duration,explicit,name,artist_genres_list,main_genre
0,2022,au,169,280161,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,FAUX,Wake Me Up,"[pop rap, pop, pop dance, dance pop, edm]",Pop
1,2022,be,182,59603,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,FAUX,Wake Me Up,"[pop rap, pop, pop dance, dance pop, edm]",Pop
2,2022,ie,184,46016,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,FAUX,Wake Me Up,"[pop rap, pop, pop dance, dance pop, edm]",Pop
3,2022,cz,198,43421,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,FAUX,Wake Me Up,"[pop rap, pop, pop dance, dance pop, edm]",Pop
4,2022,be,159,62915,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,FAUX,Wake Me Up,"[pop rap, pop, pop dance, dance pop, edm]",Pop

In [9]:
genres_df = pd.DataFrame({"genre_id": [i for i in range(1, len( list( genre_map.keys() ) ) +1)],"main_genre": list(genre_map.keys())})
genres_df

   genre_id         main_genre
0         1                pop
1         2        hip hop/rap
2         3   electronic/dance
3         4              latin
4         5           r&b/soul
5         6               rock
6         7       country/folk
7         8    global/regional
8         9  alternative/indie
9        10   reggae/dancehall

In [10]:
# rename main_genre and export as a csv
genres_df = genres_df.rename(columns={'main_genre': 'genre_name'})
genres_df.to_csv("genre.csv", index=False, encoding="utf-8", sep=";")

In [11]:
# same case
df['main_genre'] = df['main_genre'].str.lower()
genres_df['genre_name'] = genres_df['genre_name'].str.lower()

# merge
df = df.merge(genres_df, left_on='main_genre', right_on='genre_name', how='left')

In [12]:
# kepp the columns we want
track_genre = df[['track_id', 'genre_id']].copy()
track_genre = track_genre.rename(columns={'track_id': 'trackID'})

# drop duplicates
track_genre = track_genre.drop_duplicates().reset_index(drop=True)

# auto id
track_genre.insert(0, 'id', range(1, len(track_genre) + 1))

# csv 
track_genre.to_csv("track_genre.csv", index=False, encoding="utf-8", sep=";")

In [13]:
# keep columns for the track file
track_df = df[['track_id', 'duration', 'name', 'explicit']].copy()
track_df = track_df.rename(columns={
    'track_id': 'trackID',
    'name': 'title'
})

# float for duration (becauseit wasnt updated)
track_df['duration'] = track_df['duration'].astype(float)

#  'FAUX'/'VRAI' or 'False'/'True'
track_df['explicit'] = track_df['explicit'].apply(
    lambda x: 1 if str(x).strip().upper() in ['VRAI', 'TRUE'] else 0
)

# Remove duplicates
track_df = track_df.drop_duplicates().reset_index(drop=True)

# clean (but not working)
track_df['title'] = track_df['title'].str.encode('utf-8', errors='ignore').str.decode('utf-8')

df['title'] = 'Wake Me Up'

# csv
track_df.to_csv("track.csv", index=False, encoding="utf-8-sig", sep=";")

In [14]:
# clean
track_df['title'] = track_df['title'].str.encode('utf-8', errors='ignore').str.decode('utf-8')

# csv
track_df.to_csv("track.csv", index=False, encoding="utf-8-sig", sep=";")

In [15]:
# preparation charts
country = pd.read_csv('country.csv', sep=';')
country

    country_id country_code    country_name
0            1           au       Australia
1            2           be         Belgium
2            3           ie         Ireland
3            4           cz  Czech Republic
4            5           ch     Switzerland
..         ...          ...             ...
71          72           eg           Egypt
72          73           by         Belarus
73          74           ng         Nigeria
74          75           pk        Pakistan
75          76           kz      Kazakhstan

[76 rows x 3 columns]

In [46]:
df

,date,country,position,streams,track_id,artists,artist_genres,duration,explicit,name,artist_genres_list,main_genre,genre_id,genre_name
0,2022,au,169,280161,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,FAUX,Wake Me Up,"[pop rap, pop, pop dance, dance pop, edm]",pop,1.0,pop
1,2022,be,182,59603,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,FAUX,Wake Me Up,"[pop rap, pop, pop dance, dance pop, edm]",pop,1.0,pop
2,2022,ie,184,46016,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,FAUX,Wake Me Up,"[pop rap, pop, pop dance, dance pop, edm]",pop,1.0,pop
3,2022,cz,198,43421,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,FAUX,Wake Me Up,"[pop rap, pop, pop dance, dance pop, edm]",pop,1.0,pop
4,2022,be,159,62915,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,FAUX,Wake Me Up,"[pop rap, pop, pop dance, dance pop, edm]",pop,1.0,pop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540427,2019,do,200,8965,3w6HBymB6v99gmhz4aiX1g,['Kany García'],"['latin pop', 'puerto rican pop']",201600,FAUX,Para Siempre,"[latin pop, puerto rican pop]",pop,1.0,pop
540428,2020,do,200,12391,3w6HBymB6v99gmhz4aiX1g,['Kany García'],"['latin pop', 'puerto rican pop']",201600,FAUX,Para Siempre,"[latin pop, puerto rican pop]",pop,1.0,pop
540429,2022,do,200,13974,3w6HBymB6v99gmhz4aiX1g,['Kany García'],"['latin pop', 'puerto rican pop']",201600,FAUX,Para Siempre,"[latin pop, puerto rican pop]",pop,1.0,pop
540430,2020,th,200,49547,3TZ7NHkMT82AhwuYsd00Hz,['BTS'],"['k-pop boy group', 'k-pop']",245146,FAUX,Your eyes tell,"[k-pop boy group, k-pop]",pop,1.0,pop
540431,2020,be,200,44950,4zfih9sHVVJMb0f7LRoAz8,['Jul'],"['francoton', 'rap marseille']",237586,VRAI,Sousou,"[francoton, rap marseille]",hip hop/rap,2.0,hip hop/rap

In [16]:
# auto id df for initial charts
df['id'] = range(1, len(df) + 1)

In [17]:
# merge
charts_track = df.merge(country, left_on='country', right_on='country_code', how='left')

In [24]:
charts_track.columns

Index(['date', 'country', 'position', 'streams', 'track_id', 'artists',
       'artist_genres', 'duration', 'explicit', 'name', 'artist_genres_list',
       'main_genre', 'genre_id', 'genre_name', 'title', 'id', 'country_id',
       'country_code', 'country_name'],
      dtype='object')

In [29]:
charts = charts_track.rename(columns={'track_id': 'trackID'})[
    ['trackID', 'date', 'streams', 'position', 'country_id']
]
charts['chart_id'] = range(1, len(charts) + 1)

charts

                       trackID  date  streams  position  country_id  chart_id
0       0nrRP2bk19rLc0orkWPQk2  2022   280161       169         1.0         1
1       0nrRP2bk19rLc0orkWPQk2  2022    59603       182         2.0         2
2       0nrRP2bk19rLc0orkWPQk2  2022    46016       184         3.0         3
3       0nrRP2bk19rLc0orkWPQk2  2022    43421       198         4.0         4
4       0nrRP2bk19rLc0orkWPQk2  2022    62915       159         2.0         5
...                        ...   ...      ...       ...         ...       ...
275567  4hLpFMWFlXRwmO0RvR8Pau  2022    14952       200        42.0    275568
275568  1w2hClDL1xH4FPZIipZ1FJ  2022    10512       200        68.0    275569
275569  5DDbBY763OCil7Joc4YS1m  2022     6668       200        53.0    275570
275570  4iMigesJsEKt8JczIwUrBO  2022   258147       200        63.0    275571
275571  3w6HBymB6v99gmhz4aiX1g  2022    13974       200        56.0    275572

[275572 rows x 6 columns]

In [30]:
# export CSV
charts.to_csv("charts_.csv", index=False, encoding="utf-8", sep=";")

In [31]:
# charts_country table
chart_country = charts[['chart_id', 'country_id']].copy()

# auto id
chart_country['id'] = range(1, len(chart_country) + 1)

# keep what you need
chart_country = chart_country[['id', 'chart_id', 'country_id']]

# export CSV
chart_country.to_csv('chart_country.csv',index=False, encoding="utf-8", sep=";")